
   
name: Release wheels
 
on:
  release:
    types:
      - created

jobs:
 dist_linux:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/cloud-marketplace-containers/google/bazel:3.0.0
    steps:
    - uses: actions/checkout@v2
  
    # Used to host cibuildwheel
    - uses: actions/setup-python@v2

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.2.0a1

    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse
    - name: Upload
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: wheelhouse/*.whl